---
title: "California Fire Project"
output:
  html_document: default
  pdf_document: 
    fig_caption: yes
date: '2022-05-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Set your working directory and get your fire data into R
getwd()
setwd("/Users/madikindberg/Desktop/ANS 198")
list.files()
ca_fires2 = read.csv("Fire_Project.csv")

##Make sure your data uploaded correctly and begin to understand columns and rows
ca_fires2

##Make these filters in order to subset data for each year to its own table 
ca_fires2_2013 = filter(ca_fires2, Started == 2013)
ca_fires2_2014 = filter(ca_fires2, Started == 2014)
ca_fires2_2015 = filter(ca_fires2, Started == 2015)
ca_fires2_2016 = filter(ca_fires2, Started == 2016)
ca_fires2_2017 = filter(ca_fires2, Started == 2017)
ca_fires2_2018 = filter(ca_fires2, Started == 2018)
ca_fires2_2019 = filter(ca_fires2, Started == 2019)

##Install these packages to make a map of California (choose no for everything when loading packages -- unless it is not working by saying "no")
install.packages("ggplot2")

install.packages("ggmap")

install.packages("maps")

install.packages("mapdata")

library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)

##Install these packages to begin summarizing the total amount of acres burned in a single county for each individual year
install.packages("tidyverse")

install.packages("tidymodels")

no

install.packages("janitor")

install.packages("glmnet")

no

install.packages("effects")

no

install.packages("olsrr")

no

install.packages("dplyr")

library(tidyverse)
library(tidymodels)
library(janitor)
library(glmnet)
library(effects)
library(olsrr)
library(dplyr)

##Start summarizing the total amount of acres burned in a single county for all counties in each individual year
#Summary for 2013
ca_2013 = ca_fires2_2013 %>%
  group_by(Counties) %>%
  summarise(Sum = sum(AcresBurned))
  
ca_2013

#Summary for 2014
ca_2014 = ca_fires2_2014 %>%
  group_by(Counties) %>%
  summarise(Sum = sum(AcresBurned))
  
ca_2014

#Summary for 2015
ca_2015 = ca_fires2_2015 %>%
  group_by(Counties) %>%
  summarise(Sum = sum(AcresBurned))
  
ca_2015

#Summary for 2016
ca_2016 = ca_fires2_2016 %>%
  group_by(Counties) %>%
  summarise(Sum = sum(AcresBurned))
  
ca_2016

#Summary for 2017
ca_2017 = ca_fires2_2017 %>%
  group_by(Counties) %>%
  summarise(Sum = sum(AcresBurned))
  
ca_2017

#Summary for 2018
ca_2018 = ca_fires2_2018 %>%
  group_by(Counties) %>%
  summarise(Sum = sum(AcresBurned))
  
ca_2018

#Summary for 2019
ca_2019 = ca_fires2_2019 %>%
  group_by(Counties) %>%
  summarise(Sum = sum(AcresBurned))
  
ca_2019


##Start outlining maps and learning how to use the map_data
#For starters, this will show us the map of California
usa = map_data("usa")
states= map_data("state")
dim(states)

ca_df= subset(states, region == "california")

ca_base= ggplot(data=ca_df, mapping= aes(x=long, y=lat,       group=group)) +
  coord_fixed(1.3) +
  geom_polygon(color = "black", fill = "gray")

ca_base + theme_nothing()

#Now explore showing the counties of California on the map
counties = map_data("county")

ca_county = subset(counties, region== "california")

ca_base + theme_nothing() +
  geom_polygon(data = ca_county, fill = NA, color = "white") +
  geom_polygon(color = "black", fill=NA)

##Let's focus on plotting our data on the California counties map now
library(stringr)
library(dplyr)

#This will give us a shortcut to Acres Burned data we will focus on 
fire_per_mile = ca_fires2$AcresBurned

fire_per_mile

#Refresh your memory of the table column names
colnames(ca_fires2)

##Tolower will allow us to lowercase our "Counties" names in our data in order to align it will the California map data that is also lowercase which allows us to join and plot our data on the map
#Use this for each year so that all our plots will join easily with the map
ca_fires2$Counties2 = tolower(ca_fires2$Counties)
ca_fires2$Counties2

ca_2013$Counties2013 = tolower(ca_2013$Counties)
ca_2013$Counties2013

ca_2014$Counties2014 = tolower(ca_2014$Counties)
ca_2014$Counties2014

ca_2015$Counties2015 = tolower(ca_2015$Counties)
ca_2015$Counties2015

ca_2016$Counties2016 = tolower(ca_2016$Counties)
ca_2016$Counties2016

ca_2017$Counties2017 = tolower(ca_2017$Counties)
ca_2017$Counties2017

ca_2018$Counties2018 = tolower(ca_2018$Counties)
ca_2018$Counties2018

ca_2019$Counties2019 = tolower(ca_2019$Counties)
ca_2019$Counties2019

##Put description here!! Why do we need elbow room??
#Put description here!! Why do we need ditch the axis??

ditch_the_axes = theme(axis.text = element_blank(),
                       axis.line = element_blank(),
                       axis.ticks = element_blank(),
                       panel.border = element_blank(),
                       panel.grid = element_blank(),
                       axis.title = element_blank()
)

elbow_room1 = ca_base +
  geom_polygon(data = ca_fires2, aes(fill = fire$AcresBurned), color = "white") +
  geom_polygon(color = "black", fill= NA) +
  theme_bw() +
  ditch_the_axes

elbow_room1 + scale_fill_gradient(trans = "log10")

##Put description here!! What is the purpose of ca_countymap 1 and 2?
ca_countymap = ca_base + theme_nothing() +
  geom_polygon(data = ca_county, fill = NA, color = "white") +
  geom_polygon(color = "black", fill=NA)
ca_countymap

#Now we can finally join our data with the California map data 
#Essentially this will overlap our columns for counties in each set of data
#For the California map data, the counties are found under "subregion"
#For our fire data, the counties are found under "Counities'Year'"
ca_countymap2 = ca_county %>%
  left_join(ca_fires2, by = c("subregion" = "Counties2"))
ca_countymap2

ca_countymap2013 = ca_county %>%
  left_join(ca_2013, by = c("subregion" = "Counties2013"))
ca_countymap2013

ca_countymap2014 = ca_county %>%
  left_join(ca_2014, by = c("subregion" = "Counties2014"))
ca_countymap2014

ca_countymap2015 = ca_county %>%
  left_join(ca_2015, by = c("subregion" = "Counties2015"))
ca_countymap2015

ca_countymap2016 = ca_county %>%
  left_join(ca_2016, by = c("subregion" = "Counties2016"))
ca_countymap2016

ca_countymap2017 = ca_county %>%
  left_join(ca_2017, by = c("subregion" = "Counties2017"))
ca_countymap2017

ca_countymap2018 = ca_county %>%
  left_join(ca_2018, by = c("subregion" = "Counties2018"))
ca_countymap2018

ca_countymap2019 = ca_county %>%
  left_join(ca_2019, by = c("subregion" = "Counties2019"))
ca_countymap2019

#Making the intial graph for all years
acresmap = ca_base +
  geom_polygon(data = ca_countymap2,  aes(fill = AcresBurned),
               color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes
acresmap

#Adding layers to our intial map for all years
acresmap2 = acresmap + 
  ggtitle("Acres Burned in California 2013-2019") +
  scale_fill_gradientn(colors = rev(rainbow(7)),
                      breaks = c(10, 100, 1000, 10000, 250000),
                      trans = "log10")
acresmap2

#Making the initial graph for 2013
acresmap2013 = ca_base +
  geom_polygon(data = ca_countymap2013,  aes(fill = Sum),
               color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes
acresmap2013

#Adding layers to our intial map for 2013
acresmap2013B = acresmap2013 + 
  ggtitle("Acres Burned in California 2013") +
  scale_fill_gradientn(colors = rev(rainbow(7)),
                      breaks = c(10, 100, 1000, 10000, 250000),
                      trans = "log10")
acresmap2013B


#Making the initial graph for 2014
acresmap2014 = ca_base +
  geom_polygon(data = ca_countymap2014,  aes(fill = Sum),
               color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes
acresmap2014

#Adding layers to our intial map for 2014
acresmap2014B = acresmap2014 + 
  ggtitle("Acres Burned in California 2014") +
  scale_fill_gradientn(colors = rev(rainbow(7)),
                      breaks = c(10, 100, 1000, 10000, 250000),
                      trans = "log10")
acresmap2014B


#Making the initial graph for 2015
acresmap2015 = ca_base +
  geom_polygon(data = ca_countymap2015,  aes(fill = Sum),
               color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes
acresmap2015

#Adding layers to our intial map for 2015
acresmap2015B = acresmap2015 + 
  ggtitle("Acres Burned in California 2015") +
  scale_fill_gradientn(colors = rev(rainbow(7)),
                      breaks = c(10, 100, 1000, 10000, 250000),
                      trans = "log10")
                      
acresmap2015B


#Making the initial graph for 2016
acresmap2016 = ca_base +
  geom_polygon(data = ca_countymap2016,  aes(fill = Sum),
               color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes
acresmap2016

#Adding layers to our intial map for 2016
acresmap2016B = acresmap2016 + 
  ggtitle("Acres Burned in California 2016") +
  scale_fill_gradientn(colors = rev(rainbow(7)),
                      breaks = c(10, 100, 1000, 10000, 250000),
                      trans = "log10")
acresmap2016B


#Making the initial graph for 2017
acresmap2017 = ca_base +
  geom_polygon(data = ca_countymap2017,  aes(fill = Sum),
               color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes
acresmap2017

#Adding layers to our intial map for 2017
acresmap2017B = acresmap2017 + 
  ggtitle("Acres Burned in California 2017") +
  scale_fill_gradientn(colors = rev(rainbow(7)),
                      breaks = c(10, 100, 1000, 10000, 250000),
                      trans = "log10")
acresmap2017B


#Making the initial graph for 2018
acresmap2018 = ca_base +
  geom_polygon(data = ca_countymap2018,  aes(fill = Sum),
               color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes
acresmap2018

#Adding layers to our intial map for 2018
acresmap2018B = acresmap2018 + 
  ggtitle("Acres Burned in California 2018") +
  scale_fill_gradientn(colors = rev(rainbow(7)),
                      breaks = c(10, 100, 1000, 10000, 250000),
                      trans = "log10")
acresmap2018B


#Making the initial graph for 2019
acresmap2019 = ca_base +
  geom_polygon(data = ca_countymap2019,  aes(fill = Sum),
               color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes
acresmap2019

#Adding layers to our intial map for 2019
acresmap2019B = acresmap2019 + 
  ggtitle("Acres Burned in California 2019") +
  scale_fill_gradientn(colors = rev(rainbow(7)),
                      breaks = c(10, 100, 1000, 10000, 250000),
                      trans = "log10")
acresmap2019B
